name: trigger rootbuild
on:
  push:
    branches:
      - main
    
jobs:
  build:
    name: Dispatch rootbuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18
          cache: npm

      - name: Install
        run: npm install
          
      - name: Build
        run: npm run build
        
      - name: Emit rootbuild repository_dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.BOTS_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/MCSEvolved/frontend-root/dispatches \
            -d '{
                "event_type": "rootbuild"
            }'
